site_name: "JACK Wei Sun Homepage"
markdown: redcarpet
pygments: true

exclude: ['README.md']

# server configuation
baseurl: ""
# url: http://localhost:4000/
url: http://www.jkcrazy.net/

# site configuation

JK:
  name: "Jack Sun (孙伟)"
  title: "My Little Stack"
  info:
    github: "jacksunwei"
    email: "jacksunwei [at] gmail.com"
    googleplus: ""
  analytics:
    google:
      tracking_id: "UA-42599176-4"
  pages:
    blog:
      name: "Tech Blog"
      addr: "http://blog.jkcrazy.net"
    life:
      name: "Life Record"
      addr: "http://life.jkcrazy.net"
  navs:
    - title: Jack Sun (孙伟)
      menus:
        - menu: home
          url: home.html
        - menu: resume
          url: '#'
        - menu: contact
          url: contact.html
    - title: Academics
      menus:
        - menu: teaching
          url: teaching.html
        - menu: deadlines
          url: deadlines.html
        - menu: research
          url: research.html
    - title: Experiences & Projects
      menus:
        - menu: portfolio
          url: portfolio.html
        - menu: experience
          url: experience.html
    - title: Links
      menus:
        - menu: articles
          url: articles.html
        - menu: books
          url: books.html
        - menu: should-knows
          url: should-knows.html
        - menu: utilities
          url: utilities.html
        - menu: snippets
          url: snippets.html

